set(_AMENT_PACKAGE_NAME "th02_a7_description")
set(th02_a7_description_VERSION "0.2.6")
set(th02_a7_description_MAINTAINER "Westwoodrobotics <info@westwoodrobotics.io>")
set(th02_a7_description_BUILD_DEPENDS )
set(th02_a7_description_BUILDTOOL_DEPENDS "ament_cmake")
set(th02_a7_description_BUILD_EXPORT_DEPENDS )
set(th02_a7_description_BUILDTOOL_EXPORT_DEPENDS )
set(th02_a7_description_EXEC_DEPENDS )
set(th02_a7_description_TEST_DEPENDS )
set(th02_a7_description_GROUP_DEPENDS )
set(th02_a7_description_MEMBER_OF_GROUPS )
set(th02_a7_description_DEPRECATED "")
set(th02_a7_description_EXPORT_TAGS)
list(APPEND th02_a7_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
